### ISSUE TITLE
F_Log(E_LogLevel.eTrace, 'bTrace was TRUE');  It does not work

### ISSUE THREAD

**Issue by runtimevic** [mbc-engineering/log4TC#16]
Hello,
They all work for me, except:
F_Log(E_LogLevel.eTrace, 'bTrace was TRUE');
I don't understand why it doesn't log E_LogLevel.eTrace and all the others work correctly.
thank you, Víctor.

**Comment by stegm** [comment]
Can you post your log4tc config and also your NLog config?

**Comment by runtimevic** [comment]
> Can you post your log4tc config and also your NLog config?

Hello, 
by default I have not touched anything in the 2 files
=====================
appsettings.json:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "Outputs": [
    {
      "Type": "nlog"
    }
  ]
}
============================
NLog.config:

<?xml version="1.0" encoding="utf-8" ?>
<nlog
	xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	throwConfigExceptions="true"
	autoReload="true"
	internalLogLevel="Info"
	throwExceptions="true">

  

  <extensions>
    <add assembly="Mbc.Log4Tc.Output.NLog"/>
  </extensions>

  <variable name="logdir" value="${specialfolder:folder=CommonApplicationData}\log4TC\log"/>

  <targets>
    <target name="xmlLogFile"
            xsi:type="File"
            createDirs="true"
            encoding="utf-8"
            archiveFileName="${logdir}/log4tc.xml.{#}"
		    fileName="${logdir}/log4tc.xml"
		    maxArchiveFiles="1"
            archiveAboveSize="1048576"
			archiveNumbering="Rolling"
			layout="${mbclog4jxmlevent:includeAllProperties=true:message=${message} [${mbc-all-event-properties}]}">
    </target>

    <target name="textLogFile"
            xsi:type="File"
            createDirs="true"
            encoding="utf-8"
            archiveFileName="${logdir}/log4tc.log.{#}"
		    fileName="${logdir}/log4tc.log"
		    maxArchiveFiles="1"
            archiveAboveSize="1048576"
			archiveNumbering="Rolling"
			layout="${longdate}|${level:uppercase=true}|${logger}|${message}|[${mbc-all-event-properties}]">
    </target>
	
	<target name="csvLogFile"
            xsi:type="File"
            createDirs="true"
            encoding="utf-8"
            archiveFileName="${logdir}/log4tc.csv.{#}"
		    fileName="${logdir}/log4tc.csv"
		    maxArchiveFiles="1"
            archiveAboveSize="1048576"
			archiveNumbering="Rolling">
			<layout xsi:type="CsvLayout"
					withHeader="true"
					delimiter="Tab">
				<column name="time" layout="${longdate}" />
				<column name="temp" layout="${event-properties:item=temperature}" />
			</layout>
    </target>
	
  </targets>

  <rules>
    
    <logger name="*" minlevel="Debug" writeTo="xmlLogFile" />
    <logger name="*" minlevel="Debug" writeTo="textLogFile" />
	<logger name="*" minlevel="Info" writeTo="csvLogFile">
		<filter defaultAction="Ignore">
			<when condition="${event-properties:item=csv})" action="Log" />
		</filter>
	</logger>
  </rules>

</nlog>

**Comment by stegm** [comment]
Ok, in this case take a log at the NLog.config on this lines:

```
    <!--Levels: Trace, Debug, Info, Warn, Error, Fatal, Off-->
    <logger name="*" minlevel="Debug" writeTo="xmlLogFile" />
    <logger name="*" minlevel="Debug" writeTo="textLogFile" />
```
The attribute "minlevel" filters out all messages below the given value (in this case trace level). Just change it to "Trace", restart the service and try again.

Please close the issue if anything is working.

**Comment by stegm** [comment]
Close this issue because it seems to be solved
