### ISSUE TITLE
PROD ready? How the licensing works?

### ISSUE THREAD

**Issue by dkleber89** [mbc-engineering/log4TC#3]
I found this a few days ago.

I was curious about it and install it on my system for some testing. It´s exactly what im seeking for my smarthome project. It´s a simple und perfectly working solution for my case to write some logs to my graylog instance. So thank you for this work.

I have two Questions:
First: Is it production ready at this time? When not how is looking the roadmap to production ready state?
Second: This Beckhoff Lib need a License Key -> Does it cost something and how much? It´s a one time purchase or a subscription? And how can i get this license?

Thanks for your Feedback,
dkleber89

**Comment by bqstony** [comment]
Hi, i am happy about your interest.

Currently there is a licence required. This is because we have first created log4TC for use with our customers only. 
We are now in progress to remove the licence. So give us some time for this, see #2 
Yes it is used in production.

**Comment by dkleber89** [comment]
Thanks for your fast feedback ... I am looking forward when the changes are done
